name: restaurant_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  unicons: ^3.0.0
  http: ^1.2.2
  provider: ^6.1.2
  smooth_star_rating_nsafe: ^1.0.0+1
  shared_preferences: ^2.3.3
  sqflite: ^2.4.1
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.1.5
  flutter_timezone: ^4.0.0
  timezone: ^0.9.4
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      ref: b783000
  test: ^1.25.7
  mocktail: ^1.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
